### PR TITLE
[WIP, Testing Req] Feature: USB Protection Dameon

### PR DESCRIPTION
**Pull request by ItzSwirlz**
From upstream gsd-usb-protection. Removed on_screen_locked stuff, added 
gsettings_desktop_dep as a meson build dependency.

Testing required (will be done by me)

### CODE REVIEW

**Comment by ItzSwirlz** [comment]
The gschemas need updating work with enums; i'll work on it tomorrow

**Comment by ItzSwirlz** [comment]
ill include the recent commit about the symlinks with meson and all that fixes the cinnamon gdbus issue once this gets merged probably.

**Comment by clefebvre** [comment]
Can we discuss why this is needed? and if it is, why it should be part of the DE (as opposed to something like systemd or the DM itself)?

**Comment by ItzSwirlz** [comment]
# #

> Can we discuss why this is needed?

Yep. This is a feature (obviously) that integrates with usbguard. You can think of it as choosing if we want to allow the device by default or reject it. At first, this was really made to disable USB while the lock screen is on. As of https://github.com/GNOME/gnome-settings-daemon/commit/03eac7deb59e59e995fba98d3d5a6b40860c9922#diff-aeadac3b65718d641bfb5922277a88c0e7e17e85d11cd70818dc63abe1cd5eb8:

```
This change adds the ability to make use of UBSGuard to disable new USB
devices while the lockscreen is on. Note that USBGuard as of 0.7.5 is
needed.

In order to make use of this feature, you need to enable it first,
e,g, through gsettings set org.gnome.desktop.privacy usb-protection true.
And you need to have USBGuard installed, of course. Beware though: With the
default configuration the user is likely to be locked out of their
system. We encourage downstreams to change the default configuration
value s.t. USB devices are enabled unless a rule explicitly blocks them.
We take some care about users in that we allow keyboards and hardwired
devices, though.

The intended behaviour is: If the lockscreen is on, newly inserted USB
devices will not be accepted. A notification is given to the user that
they have to unlock the session and re-plug the device.
```

Of course I removed the lockscreen stuff (Because it broke things and would probably be worth getting back to later) so it's more of a connection with usbguard at the moment.



> (as opposed to something like systemd or the DM itself)?

usbguard has it's own services and stuff (from looking at apt during installing it). 



> why this is needed? and if it is, why it should be part of the DE

For something like this that would be thrown around, and currently seems like it isn't used by default in GNOME, then ignoring this idea is something I'm cool with, if you disapprove that's fine; I just thought it might be a cool thing to add.

Speaking of other cool things, maybe netbook support soon?

Anyways: yeah that's my tedtalk. I have no strong feelings one way or the other, so I'd be okay with a reject from you.

**Comment by ItzSwirlz** [comment]
I think I'm going to close this, leave the OG repo open for a day before I probably archive the usb-protection plugin folder then i'l delete the repo. Probably not worth investing to if we want to cleanup deprecated stuff pre-gtk4

**Pull request closed without merging**
