### PR TITLE
[WIP] Adapt c-s-d to Mutter 3.36.9 rebase

### PR DESCRIPTION
**Pull request by mtwebster**
This is just an experiment.
Depends on linuxmint/muffin#601.

### CODE REVIEW

**Comment by Fantu** [comment]
@mtwebster I don't see this part moved from gnome-settings-daemon to mutter nor implemented in muffin 5.2 PR, maybe I'm a bit tired and from a search I missed something about the settings after removing the cinnamon part and here, sorry if my question is stupid: where is the sound player settings code now?

**Comment by mtwebster** [comment]
It was done in Cinnamon here: https://github.com/linuxmint/cinnamon/commit/7ab95f0639d760b3b1403c7fe8b49048ac24544c (the commit you fixed earlier) - it's accessed via `global.display.get_sound_player()`.

It's probably still in g-s-d because there are other desktops that use mutter as a separate window manager and can't access its sound player the way we can.

I'm definitely not blindly mirroring other gnome packages into cinnamon's either - that would cause a lot more problems than any benefits we might get for now - . I'm adapting as needed, and where I can, eliminating overhead (For instance, I'm working on getting rid of using libgnomekbd at the moment).

**Comment by Fantu** [comment]
@mtwebster thanks for reply. you are right that not completely follow the gnome components if counterproductive or leave unnecessary stuff. Now I read well the commit comment on cinnamon and remove of sounds volume control which was almost unused and not working well so maybe it's okay to leave it like now.

**Comment by Fantu** [comment]
@mtwebster I tested sounds plugin remove (I did also a PR with csd version increase and files remove: https://github.com/linuxmint/cinnamon-settings-daemon/pull/350) and sounds are still working, the only regression I found from some fast tests is "play buttons" on sounds setting window don't working:
sounds-settings
I don't have time now to find/change it in cinnamon code and test it

**Comment by mtwebster** [comment]
I need to switch those to use something else also (they were using c-s-d also).

**Comment by Fantu** [comment]
github search it seemed better to me before but does not even find some simple exact matches in some cases :(
from a fast grep on local repository copy in cinnamon I found files/usr/share/cinnamon/cinnamon-settings/modules/cs_sound.py and files/usr/share/cinnamon/cinnamon-settings/bin/cs_sound.py that still use it

**Comment by mtwebster** [comment]
I fixed: https://github.com/linuxmint/cinnamon/pull/10372/commits/2a08e42dc2cb67a0a370df2be9e5ce9c1075b785

**Comment by Fantu** [comment]
@mtwebster sry I saw only after your new commit, now I'll rebuild cinnamon and I'll retest

**Comment by Fantu** [comment]
@mtwebster thanks for merging debian improvements, I did another commit now about etc files removed, I had forgotten with removed some plugins to check the conffiles, I only noticed it today from a quick look at the errors in the logs from the last test: https://github.com/linuxmint/cinnamon-settings-daemon/pull/358

**Comment by mtwebster** [comment]
@Fantu sorry, fixed the readme and merged. Please don't hesitate to bug me sooner if I don't act on stuff like that, I get distracted and am forgetful.

**Comment by Fantu** [comment]
@mtwebster https://github.com/linuxmint/cinnamon-settings-daemon/commit/3e820059b5d7faf4e363efa5becb17d0e8526811 is missed, a "git rebase master" can be done fast and without conflict, I already tested it here: https://github.com/fantu/cinnamon-settings-daemon/commits/muffin-5.2-test

**Comment by mtwebster** [comment]
Thanks

**Comment by Fantu** [comment]
@mtwebster 2 commit from master are missed, are tested on my latest build is possible a fast rebase without conflict ( https://github.com/fantu/cinnamon-settings-daemon/commits/muffin-5.2-test )

**Pull request merged**
