### PR TITLE
Deprecation warning cleanup while removing some whitespaces

### PR DESCRIPTION
**Pull request by ItzSwirlz**
This is like 1/4 of the problems but anyways:

gdk_display_get_device_manager -> gdk_display_get_default_seat

gtk_show_uri -> gtk_show_uri_on_window

Remove unused vars *l, conflicting_options

gtk_image_new_from-stock -> gtk_image_new_from_icon_name

gdk_keymap_get_default -> gdk_keymap_get_for_display (in some cases)

gtk_image_menu_item_new_with_label -> gtk_menu_item_new_with_label

up_client_get_devices -> up_client_get_devices2

gdk_screen_get_monitor_at_point -> gdk_display_get_monitor_at_point

Also, my editor Atom automatically removes whitespaces mostly when I open a file/make a change and save it. If you want to start removing, before commiting I suggest you open the file to remove the whitespaces.

### CODE REVIEW

**Comment by Fantu** [comment]
an update of gdk version is needed in meson.build and debian/control, for example gdk_display_get_default_seat was added in 3.20, gdk_display_get_monitor_at_point in 3.22
and also upower-glib, up_client_get_devices2 was added in 0.99.8 and after some compatibility code with older upower can be removed

**Comment by Fantu** [comment]
in debian/control you increased libglib2.0-dev instead of libgtk-3-dev

**Comment by ItzSwirlz** [comment]
oopsies

**Comment by Fantu** [comment]
in case like this (in PR) is better amend the commit and force the push instead create new commit

**Comment by ItzSwirlz** [comment]
I think it should be fine.

**Comment by mtwebster** [comment]
I'm closing this - there are far too many issues, I didn't comment on all of them. You need to pay attention to what functions require as arguments and above all, you need to test these things. I think probably all of the issues here should have complained during compilation. And for sure things would be broken if some how this managed to compile.

If you fix this stuff at a later point we can open this back up.

**Pull request closed without merging**
