### PR TITLE
Port share plugin so vino/rygel works

### PR DESCRIPTION
**Pull request by leigh123linux**
Ported from gnome-settings-daemon

should fix https://github.com/linuxmint/Cinnamon/issues/4477

### CODE REVIEW

**Comment by brianjmurrell** [comment]
So now that I have installed the packages from F24 testing, how do I enable sharing (and thus start vino)?  I don't see any new sharing item in cinnamon-control-center.

**Comment by leigh123linux** [comment]
@brianjmurrell 

You need to install control-center for the option to appear  in cinnamon-settings as I only ported the cinnamon-settings-daemon sharing plugin.

**Comment by brianjmurrell** [comment]
Literally ```control-centre``` or ```cinnamon-control-centre```?

```
$ sudo dnf install control-centre
Last metadata expiration check: 0:40:15 ago on Thu Sep  8 16:12:21 2016.
No package control-centre available.
Error: Unable to find a match.
```

**Comment by leigh123linux** [comment]
@brianjmurrell 

It's whatever the name that fedora used for gnome-control-center

```
$ rpm -qa control*
control-center-filesystem-3.20.1-1.fc24.x86_64
control-center-3.20.1-1.fc24.x86_64
```

**Pull request closed without merging**
