### PR TITLE
Wip/libinput support

### LINKED ISSUE #78: [Feature Request] Please add xorg-drv-input-libinput support
```
 Change xorg input stack to use libinput for the Workstation product
Summary

Replace the current (low-level) input xorg drivers with libinput using the xorg-x11-drv-libinput wrapper. This is intended to eventually happen everywhere, but for now this change is limited to the Workstation product / the gnome-desktop.
Owner

    Name: Hans de Goede
    Email: hdegoede@redhat.com
    Release notes owner: 

Current status

    Targeted release: Fedora 22
    Last updated: November 21th 2014
    Tracker bug: #1181565 

Detailed Description

Currently xorg uses different input drivers depending on the device type. This makes it impossible to do things like middle button scrolling on the trackpoint on laptops where the trackpoint buttons are software-emulated buttons on the touchpad. Besides this the xf86-input-synaptics driver was never really designed for multi-touch touchpads and this causes various issues.

For Wayland we've been working on a new improved input stack, which is to be shared by all compositors and lives inside libinput. We plan to replace the current (low-level) input xorg drivers with libinput using the xorg-x11-drv-libinput wrapper.
Benefit to Fedora

Improved user experience wrt input devices. libinput provides a number of features that are an improvement over the current evdev/synaptics driver set:

    proper tracking of individual fingers on touchpads, improving the usability of software buttons
    automatic disable-while-typing without having to run an external process
    setting a device to left-handed doesn't change the tapping configuration
    middle top software button can be used to emulate wheel events on the trackstick (on the Lenovo *40 series and related touchpads)
    "natural scrolling" is device-wide and available on any scrolling device
    improved palm detection 

Scope

Besides xorg changes, this will also require changes to the control panel applets for mouse / touchpad configuration in the various desktop environments, as those all are hardcoded to use the xorg-x11-drv-synaptics specific interfaces. Since this requires changes to most desktop-environments the plan is to only install xorg-x11-drv-libinput by default on the Workstation product, so that for no only the GNOME desktop needs to be adjusted. When this package is installed xorg will automatically prefer it over the old input drivers.

Other desktop environment users can also install the package if they want to use the new libinput based input stack. GNOME users can uninstall it if they want to switch back to the old drivers for some reason, the modified gnome input configuration code will still be able to work with the old drivers.

    Proposal owners: 

Package libinput and xorg-drv-input-libinput (done), make sure that xorg-drv-input-libinput has the necessary config interfaces for control panel mouse/touchpad config applets (wip). Write patches for gnome-control-center mouse/touchpad capplet. Coordinate with other desktop environments.

    Other developers: 

GNOME: merge the gnome-control-center patches. Other desktops: other desktops should to start working on getting there input configuration code ready to work with xorg-x11-drv-libinput, if they are fully ready for xorg-x11-drv-libinput, we encourage them to add it to the default package set for their spin, but they will be able to keep using the old drivers if they are not ready, and we will keep supporting the old drivers for F-22.

    Release engineering: N/A 

    Policies and guidelines: N/A 

Upgrade/compatibility impact

No upgrade impact, the /usr/share/X11/xorg.conf.d rules will automatically use the new driver for relevant devices.
How To Test

Fire up new Fedora version, use keyboard, mouse and touchpads. Also try special features like 2 finger scrolling, click and drag, tap and drag, etc.
User Experience

We expect users to see a noticable improvement in touchpad behavior.

Synaptics provides some exotic options that libinput does not implement. We do not expect this to have significant impact as those options are rarely used (if at all).
Dependencies

The GNOME input configuration changes need to be merged before we can add the package to the default package-set for the Workstation product. 
```

https://fedoraproject.org/wiki/Changes/LibinputForXorg

### PR DESCRIPTION
**Pull request by whot**
version 2 of the pull request.

Fixes #78

Add libinput support. Done cooperatively with other drivers, so most of the bits toggle the bit that exists on the device. This should in theory even support two touchpads, one with synaptics and one with libinput, and just DTRT.

The keys don't all map into libinput config options, so I took a best guess where needed.

I wouldn't mind if someone could do a bit more testing though, happy to merge/squash any patches.

### CODE REVIEW

**Comment by whot** [comment]
For testing: xinput watch-props "<device name>" and then toggle the various UI elements. If the property on the driver changes in the correct manner, then the bits work correctly. Doesn't work for all options though, e.g. disable-while-typing, left-handed and accel settings aren't properties on the legacy drivers

**Comment by clefebvre** [comment]
First of all, many thanks for this. I really like the way you supported both synaptics and libinput here.

I tested as much as I could and I couldn't find regressions.

In Linux Mint, libinput takes over from synaptics for all touchpad devices as soon as it is installed. 

When libinput isn't installed, all options in Cinnamon work properly and affect the synaptics driver. This is still true after the changes brought by this PR.

When libinput is installed, the touchpad continues to work but the options in Cinnamon no longer work and the touchpad is no longer configurable. This was due to the lack of libinput support which this PR addresses. With the changes brought by this PR, most options work. Those which don't are probably failing due to limitations inherent to the libinput driver itself.

This is therefore ready to merge. I hope we'll be able to improve the mouse module in cinnamon settings so that it can show/hide relevant configuration options based on the driver being used.

**Comment by monsta** [comment]
@whot: I started adapting this to mate-settings-daemon, and there are some things I have some questions about... can you please clarify these things?

* https://github.com/linuxmint/cinnamon-settings-daemon/commit/85510232d53e8ed98697e9a7e3cc33274a531e19: setting tap to click for libinput doesn't take "left handed" setting into account... is that ok?

* https://github.com/linuxmint/cinnamon-settings-daemon/commit/c35f95210f025132e2e551024a01f6102371a0a0: well, this is related to previous question... setting "left handed" property on a Synaptics touchpad also includes calling ```set_tap_to_click``` for it to swap left and right buttons if necessary, but it's not done for libinput.

* https://github.com/linuxmint/cinnamon-settings-daemon/commit/c35f95210f025132e2e551024a01f6102371a0a0 and https://github.com/linuxmint/cinnamon-settings-daemon/commit/1e7d504a5d0003b1c71e8bcacc3476002107d414: here ```property_exists_on_device```  is used instead of ```property_from_name``` to check if a device is managed by libinput - wouldn't using ```property_from_name``` be enough?

**Comment by whot** [comment]
sure.
* in libinput tapping is handled differently so you don't have to worry about left-handed, there is no crazy button mapping needed like in synaptics, libinput will handle this for you, same applies to your second comment
* properties names are global and device independent, once initialised by any device it exists until the end of the session. so if you have (had) one device with libinput, property_from_name always returns a valid property, even if there is no device currently present that actually uses that property. that's why you need to check for the property on the device itself

**Comment by monsta** [comment]
Ok, got it. But then... shouldn't ```property_exists_on_device``` be used in other functions instead of ```property_from_name``` as well?

**Comment by monsta** [comment]
Side note: I've noticed that ```property_exists_on_device``` doesn't close the device in the end...

**Comment by whot** [comment]
oops, yeah, the missing xdevice_close() is a bug that needs to be fixed.

A quick check of the property_from_name() usage: yes, ideally they'll all use property_exists_on_device() everywhere including in the old code. right now, I think the only issues that could arise is when you have evdev + libinput simultaneously active or synaptics + libinput. But because changing properties is always "get property -> change property" the "get" part will fail and we bail, so no harm done. So right now, it's a cosmetic issue.

**Comment by monsta** [comment]
Ok, thanks.
I've submitted a fix for device closing in https://github.com/linuxmint/cinnamon-settings-daemon/pull/147.

**Pull request merged**
