### PR TITLE
Add an option to prevent handle-lid-switch from being inhibited. 

### LINKED ISSUE #141: Cinnamon settings daemon blocks systemd lid-switch action
I'm using cinnamon-settings-daemon 3.2.0-1 under Arch Linux. I just noticed that my laptop doesn't go to sleep. The cause of the problem is that cinnamon-settings-daemon inhibits handle-lid-switch, as `systemd-inhibit` reports:
```
systemd-inhibit
     Who: NetworkManager (UID 0/root, PID 306/NetworkManager)
    What: sleep
     Why: NetworkManager needs to turn off networks
    Mode: delay

     Who: marcin (UID 1000/marcin, PID 937/cinnamon-settin)
    What: handle-lid-switch
     Why: Multiple displays attached
    Mode: block

     Who: marcin (UID 1000/marcin, PID 937/cinnamon-settin)
    What: sleep
     Why: Cinnamon needs to lock the screen
    Mode: delay

     Who: marcin (UID 1000/marcin, PID 937/cinnamon-settin)
    What: handle-power-key:handle-suspend-key:handle-hibernate-key
     Why: Cinnamon handling keypresses
    Mode: block

4 inhibitors listed.
```

I want systemd to handle the lid switch action because, unlike Cinnamon, it allows me to temporarily inhibit the lid switch (via `systemd-inhibit`). AFAIK Cinnamon doesn't provide such functionality.

At least, disabling the systemd things should be voluntary.

### PR DESCRIPTION
**Pull request by marmistrz**
Closes #141.
Depends on https://github.com/linuxmint/cinnamon-desktop/pull/105

### CODE REVIEW

**Comment by marmistrz** [comment]
Should I try retrigger circleci? The _no test commands were found_ error doesn't seem to be my fault

**Comment by marmistrz** [comment]
@clefebvre as of 3.6.2 (latest stable @ Arch Linux) cinnamon-settings-daemon ignores the user inhibitor:
```
systemd-inhibit --what=handle-lid-switch --who=sleep --why=test sleep 1h
```
The following inhibitors are listed before the user inhibitor:
```
     Who: marcin (UID 1000/marcin, PID 1005/csd-power)
    What: sleep
     Why: Cinnamon needs to lock the screen
    Mode: delay

     Who: marcin (UID 1000/marcin, PID 975/csd-media-keys)
    What: handle-power-key:handle-suspend-key:handle-hibernate-key
     Why: Cinnamon handling keypresses
    Mode: block

     Who: marcin (UID 1000/marcin, PID 1005/csd-power)
    What: handle-lid-switch
     Why: Multiple displays attached
    Mode: block

     Who: UPower (UID 0/root, PID 1047/upowerd)
    What: sleep
     Why: Pause device polling
    Mode: delay

     Who: NetworkManager (UID 0/root, PID 389/NetworkManager)
    What: sleep
     Why: NetworkManager needs to turn off networks
    Mode: delay

5 inhibitors listed.
```

An external display was **not** attached.

**Comment by clefebvre** [comment]
shouldn't

`systemd-inhibit --what=handle-lid-switch --who=sleep --why=test sleep 1h`

be this instead?

`systemd-inhibit --what=sleep --who=sleep --why=test sleep 1h`

When cinnamon tells systemd to sleep, it doesn't tell it to handle the lid event.. Cinnamon itself handles the lid event and tells Systemd to sleep.

**Comment by clefebvre** [comment]
You can also omit --what altogether to default to idle+sleep+shutdown.

**Comment by marmistrz** [comment]
The command above works if Cinnamon doesn't interfere with the systemd PM and one may, in particular, want to disable only lid-suspend (and not manual suspend, e.g. by `systemctl suspend` or the Cinnamon menus). I'll recheck what's the behavior with inhibited sleep.

**Comment by marmistrz** [comment]
Migrated the configuration option from https://github.com/linuxmint/cinnamon-desktop/pull/105#event-1576007125

**Pull request merged**
