### PR TITLE
XSettings: Set Gtk/Titlebar{Double,Middle,Right}Click

### PR DESCRIPTION
**Pull request by tanderson-google**
Fixes issue https://github.com/linuxmint/cinnamon-settings-daemon/issues/211

### CODE REVIEW

**Comment by clefebvre** [comment]
Thanks @tanderson-google,

You've a misplaced comma which prevents your changes to compile.

Can you explain also what this fixes with a simple test case? Running gcalctool, which uses client-side-decorations, I'm unable to make it follow the Cinnamon settings. Changing titlebar double click to minimize for instance, has no effect... with or without your changes.

**Comment by tanderson-google** [comment]
Thanks, I've fixed the issues.

To test, run a GTK app with client side decorations, like gtk3-widget-factory.  The titlebar double click settings should now work with the latest patch.

**Comment by tanderson-google** [comment]
Friendly ping

**Comment by clefebvre** [comment]
... I feel like an idiot. I just pushed the very same thing.

I started looking at your other PR which fixes the CSD button layout. After I moved cinnamon-settings-daemon and muffin towards the same key I wondered what other GTK settings we could set to improve support.

I'm sorry, this could have been merged.

https://github.com/linuxmint/cinnamon-settings-daemon/commit/fa55de663cac569099327bd236a3a1dc64aee1e5

**Pull request closed without merging**
