### PR TITLE
Orientation: Port plugin updates from GNOME 3.20

### PR DESCRIPTION
**Pull request by xhaakon**

### CODE REVIEW

**Comment by clefebvre** [comment]
Thanks,

Can you describe what this fixes/improves and how to test it?

**Comment by xhaakon** [comment]
Most importantly the plugin now reads orientation data from D-Bus API exposed by [iio-sensor-proxy](https://github.com/hadess/iio-sensor-proxy) (which needs to be installed), so Cinnamon no longer has to care about low-level details of how kernel drivers expose different sensor hardware. Also adding support for new accelerometers should be as simple as updating iio-sensor-proxy.

I tested this on [Lenovo Yoga 2 Pro](http://www.linlap.com/lenovo_ideapad_yoga_2_pro) where after applying the included patches Cinnamon started rotating the screen according to the laptop's physical orientation, which didn't work before. The same should apply to all devices supported in iio-sensor-proxy.

It may happen that the accelerometer starts working only after first suspending and resuming the machine; it is a known kernel bug [\[1\]](https://bugzilla.kernel.org/show_bug.cgi?id=111321)[\[2\]](https://github.com/hadess/iio-sensor-proxy/issues/66).

**Comment by clefebvre** [comment]
Thanks @xhaakon

**Comment by clefebvre** [comment]
This is ready to merge. Thanks for mentioning the upstream commit hashes in the commit messages. I wish you had given more credit to upstream committers. 

We're in the process of defining a standard for this (ideally we'd want to link to upstream bug reports and commits, but also credit the people who were involved) and it should be soon available in the developer guidelines.

Regarding the changes, they're very good. Thanks for porting these changes to Cinnamon.

**Pull request merged**
